/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderId = IDL.Text;
export const ProductId = IDL.Text;
export const DeliveryOption = IDL.Variant({
  'SameDay' : IDL.Null,
  'NextDay' : IDL.Null,
  'Standard' : IDL.Null,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'deliveryOption' : DeliveryOption,
  'quantity' : IDL.Nat,
  'selectedSize' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'Card' : IDL.Null,
  'CashOnDelivery' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Processing' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'createdAt' : Timestamp,
  'deliveryOption' : DeliveryOption,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const FulfillmentBy = IDL.Variant({
  'AdminFulfilled' : IDL.Null,
  'SellerFulfilled' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'fulfillmentBy' : FulfillmentBy,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'hasFitAndTry' : IDL.Bool,
  'sizes' : IDL.Vec(IDL.Text),
  'sellerName' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'hasSameDayDelivery' : IDL.Bool,
  'gender' : IDL.Text,
  'category' : IDL.Text,
  'sellerId' : IDL.Text,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'fulfillmentBy' : FulfillmentBy,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'hasFitAndTry' : IDL.Bool,
  'sizes' : IDL.Vec(IDL.Text),
  'sellerName' : IDL.Text,
  'orderCount' : IDL.Nat,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'hasSameDayDelivery' : IDL.Bool,
  'gender' : IDL.Text,
  'category' : IDL.Text,
  'sellerId' : IDL.Text,
  'price' : IDL.Nat,
});
export const NotificationId = IDL.Text;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'orderId' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'sellerId' : IDL.Opt(IDL.Text),
});
export const SellerId = IDL.Text;
export const Seller = IDL.Record({
  'id' : SellerId,
  'isApproved' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const SellerInput = IDL.Record({
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Measurements = IDL.Record({
  'weight' : IDL.Nat,
  'height' : IDL.Nat,
  'chest' : IDL.Nat,
  'waist' : IDL.Nat,
});
export const FitAndTryRequest = IDL.Record({
  'productId' : ProductId,
  'measurements' : Measurements,
  'preferredSize' : IDL.Text,
});

export const idlService = IDL.Service({
  'addNotification' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'cancelOrder' : IDL.Func([OrderId], [IDL.Bool], []),
  'createOrder' : IDL.Func(
      [
        IDL.Vec(CartItem),
        IDL.Text,
        DeliveryOption,
        PaymentMethod,
        IDL.Text,
        IDL.Text,
      ],
      [Order],
      [],
    ),
  'createProduct' : IDL.Func(
      [ProductInput],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
  'deleteProduct' : IDL.Func(
      [ProductId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getNotifications' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsBySeller' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getSeller' : IDL.Func([SellerId], [IDL.Opt(Seller)], ['query']),
  'getSellerByEmailOrPhone' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(Seller)],
      ['query'],
    ),
  'listOrders' : IDL.Func([], [IDL.Vec(IDL.Tuple(OrderId, Order))], ['query']),
  'listSellers' : IDL.Func([], [IDL.Vec(Seller)], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'registerSeller' : IDL.Func(
      [SellerInput],
      [IDL.Variant({ 'ok' : Seller, 'err' : IDL.Text })],
      [],
    ),
  'removeSeller' : IDL.Func([SellerId], [IDL.Bool], []),
  'submitFitAndTryRequest' : IDL.Func([FitAndTryRequest], [IDL.Text], []),
  'updateOrderStatus' : IDL.Func(
      [OrderId, OrderStatus],
      [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
      [],
    ),
  'updateProduct' : IDL.Func(
      [ProductId, ProductInput],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderId = IDL.Text;
  const ProductId = IDL.Text;
  const DeliveryOption = IDL.Variant({
    'SameDay' : IDL.Null,
    'NextDay' : IDL.Null,
    'Standard' : IDL.Null,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'deliveryOption' : DeliveryOption,
    'quantity' : IDL.Nat,
    'selectedSize' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'Card' : IDL.Null,
    'CashOnDelivery' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Processing' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'createdAt' : Timestamp,
    'deliveryOption' : DeliveryOption,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const FulfillmentBy = IDL.Variant({
    'AdminFulfilled' : IDL.Null,
    'SellerFulfilled' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'fulfillmentBy' : FulfillmentBy,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'hasFitAndTry' : IDL.Bool,
    'sizes' : IDL.Vec(IDL.Text),
    'sellerName' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'hasSameDayDelivery' : IDL.Bool,
    'gender' : IDL.Text,
    'category' : IDL.Text,
    'sellerId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'fulfillmentBy' : FulfillmentBy,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'hasFitAndTry' : IDL.Bool,
    'sizes' : IDL.Vec(IDL.Text),
    'sellerName' : IDL.Text,
    'orderCount' : IDL.Nat,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'hasSameDayDelivery' : IDL.Bool,
    'gender' : IDL.Text,
    'category' : IDL.Text,
    'sellerId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const NotificationId = IDL.Text;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'orderId' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'sellerId' : IDL.Opt(IDL.Text),
  });
  const SellerId = IDL.Text;
  const Seller = IDL.Record({
    'id' : SellerId,
    'isApproved' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SellerInput = IDL.Record({
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Measurements = IDL.Record({
    'weight' : IDL.Nat,
    'height' : IDL.Nat,
    'chest' : IDL.Nat,
    'waist' : IDL.Nat,
  });
  const FitAndTryRequest = IDL.Record({
    'productId' : ProductId,
    'measurements' : Measurements,
    'preferredSize' : IDL.Text,
  });
  
  return IDL.Service({
    'addNotification' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'cancelOrder' : IDL.Func([OrderId], [IDL.Bool], []),
    'createOrder' : IDL.Func(
        [
          IDL.Vec(CartItem),
          IDL.Text,
          DeliveryOption,
          PaymentMethod,
          IDL.Text,
          IDL.Text,
        ],
        [Order],
        [],
      ),
    'createProduct' : IDL.Func(
        [ProductInput],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
    'deleteProduct' : IDL.Func(
        [ProductId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getNotifications' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsBySeller' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getSeller' : IDL.Func([SellerId], [IDL.Opt(Seller)], ['query']),
    'getSellerByEmailOrPhone' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Seller)],
        ['query'],
      ),
    'listOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(OrderId, Order))],
        ['query'],
      ),
    'listSellers' : IDL.Func([], [IDL.Vec(Seller)], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'registerSeller' : IDL.Func(
        [SellerInput],
        [IDL.Variant({ 'ok' : Seller, 'err' : IDL.Text })],
        [],
      ),
    'removeSeller' : IDL.Func([SellerId], [IDL.Bool], []),
    'submitFitAndTryRequest' : IDL.Func([FitAndTryRequest], [IDL.Text], []),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Variant({ 'ok' : Order, 'err' : IDL.Text })],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, ProductInput],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };