/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'productId' : ProductId,
  'deliveryOption' : DeliveryOption,
  'quantity' : bigint,
  'selectedSize' : string,
}
export type DeliveryOption = { 'SameDay' : null } |
  { 'NextDay' : null } |
  { 'Standard' : null };
export interface FitAndTryRequest {
  'productId' : ProductId,
  'measurements' : Measurements,
  'preferredSize' : string,
}
export type FulfillmentBy = { 'AdminFulfilled' : null } |
  { 'SellerFulfilled' : null };
export interface Measurements {
  'weight' : bigint,
  'height' : bigint,
  'chest' : bigint,
  'waist' : bigint,
}
export interface Notification {
  'id' : NotificationId,
  'createdAt' : bigint,
  'isRead' : boolean,
  'orderId' : [] | [string],
  'message' : string,
  'sellerId' : [] | [string],
}
export type NotificationId = string;
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'total' : bigint,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'createdAt' : Timestamp,
  'deliveryOption' : DeliveryOption,
  'shippingAddress' : string,
  'items' : Array<CartItem>,
}
export type OrderId = string;
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Processing' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export type PaymentMethod = { 'Card' : null } |
  { 'CashOnDelivery' : null };
export interface Product {
  'id' : ProductId,
  'fulfillmentBy' : FulfillmentBy,
  'name' : string,
  'description' : string,
  'hasFitAndTry' : boolean,
  'sizes' : Array<string>,
  'sellerName' : string,
  'orderCount' : bigint,
  'stock' : bigint,
  'imageUrl' : string,
  'hasSameDayDelivery' : boolean,
  'gender' : string,
  'category' : string,
  'sellerId' : string,
  'price' : bigint,
}
export type ProductId = string;
export interface ProductInput {
  'fulfillmentBy' : FulfillmentBy,
  'name' : string,
  'description' : string,
  'hasFitAndTry' : boolean,
  'sizes' : Array<string>,
  'sellerName' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'hasSameDayDelivery' : boolean,
  'gender' : string,
  'category' : string,
  'sellerId' : string,
  'price' : bigint,
}
export interface Seller {
  'id' : SellerId,
  'isApproved' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'businessName' : string,
  'email' : string,
  'phone' : string,
}
export type SellerId = string;
export interface SellerInput {
  'name' : string,
  'businessName' : string,
  'email' : string,
  'phone' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addNotification' : ActorMethod<
    [string, [] | [string], [] | [string]],
    string
  >,
  'cancelOrder' : ActorMethod<[OrderId], boolean>,
  'createOrder' : ActorMethod<
    [Array<CartItem>, string, DeliveryOption, PaymentMethod, string, string],
    Order
  >,
  'createProduct' : ActorMethod<
    [ProductInput],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'deleteProduct' : ActorMethod<
    [ProductId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getNotifications' : ActorMethod<[[] | [string]], Array<Notification>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsBySeller' : ActorMethod<[string], Array<Product>>,
  'getSeller' : ActorMethod<[SellerId], [] | [Seller]>,
  'getSellerByEmailOrPhone' : ActorMethod<[string, string], [] | [Seller]>,
  'listOrders' : ActorMethod<[], Array<[OrderId, Order]>>,
  'listSellers' : ActorMethod<[], Array<Seller>>,
  'markNotificationRead' : ActorMethod<[string], boolean>,
  'registerSeller' : ActorMethod<
    [SellerInput],
    { 'ok' : Seller } |
      { 'err' : string }
  >,
  'removeSeller' : ActorMethod<[SellerId], boolean>,
  'submitFitAndTryRequest' : ActorMethod<[FitAndTryRequest], string>,
  'updateOrderStatus' : ActorMethod<
    [OrderId, OrderStatus],
    { 'ok' : Order } |
      { 'err' : string }
  >,
  'updateProduct' : ActorMethod<
    [ProductId, ProductInput],
    { 'ok' : Product } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];