/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SellerInput {
    name: string;
    businessName: string;
    email: string;
    phone: string;
}
export interface ProductInput {
    fulfillmentBy: FulfillmentBy;
    name: string;
    description: string;
    hasFitAndTry: boolean;
    sizes: Array<string>;
    sellerName: string;
    stock: bigint;
    imageUrl: string;
    hasSameDayDelivery: boolean;
    gender: string;
    category: string;
    sellerId: string;
    price: bigint;
}
export type Timestamp = bigint;
export interface FitAndTryRequest {
    productId: ProductId;
    measurements: Measurements;
    preferredSize: string;
}
export interface Seller {
    id: SellerId;
    isApproved: boolean;
    name: string;
    createdAt: bigint;
    businessName: string;
    email: string;
    phone: string;
}
export type SellerId = string;
export interface Measurements {
    weight: bigint;
    height: bigint;
    chest: bigint;
    waist: bigint;
}
export interface Order {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    total: bigint;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    createdAt: Timestamp;
    deliveryOption: DeliveryOption;
    shippingAddress: string;
    items: Array<CartItem>;
}
export type NotificationId = string;
export interface Notification {
    id: NotificationId;
    createdAt: bigint;
    isRead: boolean;
    orderId?: string;
    message: string;
    sellerId?: string;
}
export type ProductId = string;
export interface CartItem {
    productId: ProductId;
    deliveryOption: DeliveryOption;
    quantity: bigint;
    selectedSize: string;
}
export interface Product {
    id: ProductId;
    fulfillmentBy: FulfillmentBy;
    name: string;
    description: string;
    hasFitAndTry: boolean;
    sizes: Array<string>;
    sellerName: string;
    orderCount: bigint;
    stock: bigint;
    imageUrl: string;
    hasSameDayDelivery: boolean;
    gender: string;
    category: string;
    sellerId: string;
    price: bigint;
}
export type OrderId = string;
export enum DeliveryOption {
    SameDay = "SameDay",
    NextDay = "NextDay",
    Standard = "Standard"
}
export enum FulfillmentBy {
    AdminFulfilled = "AdminFulfilled",
    SellerFulfilled = "SellerFulfilled"
}
export enum OrderStatus {
    Delivered = "Delivered",
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Processing = "Processing",
    Shipped = "Shipped",
    Pending = "Pending"
}
export enum PaymentMethod {
    Card = "Card",
    CashOnDelivery = "CashOnDelivery"
}
export interface backendInterface {
    addNotification(message: string, sellerId: string | null, orderId: string | null): Promise<string>;
    cancelOrder(id: OrderId): Promise<boolean>;
    createOrder(items: Array<CartItem>, shippingAddress: string, deliveryOption: DeliveryOption, paymentMethod: PaymentMethod, customerName: string, customerPhone: string): Promise<Order>;
    createProduct(input: ProductInput): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteProduct(id: ProductId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getNotifications(sellerId: string | null): Promise<Array<Notification>>;
    getOrder(id: OrderId): Promise<Order | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    getProducts(): Promise<Array<Product>>;
    getProductsBySeller(sellerId: string): Promise<Array<Product>>;
    getSeller(id: SellerId): Promise<Seller | null>;
    getSellerByEmailOrPhone(email: string, phone: string): Promise<Seller | null>;
    listOrders(): Promise<Array<[OrderId, Order]>>;
    listSellers(): Promise<Array<Seller>>;
    markNotificationRead(notificationId: string): Promise<boolean>;
    registerSeller(input: SellerInput): Promise<{
        __kind__: "ok";
        ok: Seller;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeSeller(sellerId: SellerId): Promise<boolean>;
    submitFitAndTryRequest(req: FitAndTryRequest): Promise<string>;
    updateOrderStatus(id: OrderId, newStatus: OrderStatus): Promise<{
        __kind__: "ok";
        ok: Order;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateProduct(id: ProductId, input: ProductInput): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { CartItem as _CartItem, DeliveryOption as _DeliveryOption, FulfillmentBy as _FulfillmentBy, Notification as _Notification, NotificationId as _NotificationId, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, Product as _Product, ProductId as _ProductId, ProductInput as _ProductInput, Seller as _Seller, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addNotification(arg0: string, arg1: string | null, arg2: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async cancelOrder(arg0: OrderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return result;
        }
    }
    async createOrder(arg0: Array<CartItem>, arg1: string, arg2: DeliveryOption, arg3: PaymentMethod, arg4: string, arg5: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_vec_n2(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_DeliveryOption_n5(this._uploadFile, this._downloadFile, arg2), to_candid_PaymentMethod_n7(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return from_candid_Order_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_vec_n2(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_DeliveryOption_n5(this._uploadFile, this._downloadFile, arg2), to_candid_PaymentMethod_n7(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return from_candid_Order_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: ProductInput): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_ProductInput_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_ProductInput_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: ProductId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: string | null): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsBySeller(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsBySeller(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsBySeller(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSeller(arg0: SellerId): Promise<Seller | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeller(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeller(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSellerByEmailOrPhone(arg0: string, arg1: string): Promise<Seller | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSellerByEmailOrPhone(arg0, arg1);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSellerByEmailOrPhone(arg0, arg1);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrders(): Promise<Array<[OrderId, Order]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSellers(): Promise<Array<Seller>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSellers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSellers();
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async registerSeller(arg0: SellerInput): Promise<{
        __kind__: "ok";
        ok: Seller;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerSeller(arg0);
                return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerSeller(arg0);
            return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeSeller(arg0: SellerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSeller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSeller(arg0);
            return result;
        }
    }
    async submitFitAndTryRequest(arg0: FitAndTryRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFitAndTryRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFitAndTryRequest(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<{
        __kind__: "ok";
        ok: Order;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n41(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n41(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductInput): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n20(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n20(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CartItem_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryOption_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryOption): DeliveryOption {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_FulfillmentBy_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FulfillmentBy): FulfillmentBy {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Seller]): Seller | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    total: bigint;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    createdAt: _Timestamp;
    deliveryOption: _DeliveryOption;
    shippingAddress: string;
    items: Array<_CartItem>;
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    total: bigint;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    createdAt: Timestamp;
    deliveryOption: DeliveryOption;
    shippingAddress: string;
    items: Array<CartItem>;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n11(_uploadFile, _downloadFile, value.status),
        total: value.total,
        paymentMethod: from_candid_PaymentMethod_n13(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        deliveryOption: from_candid_DeliveryOption_n15(_uploadFile, _downloadFile, value.deliveryOption),
        shippingAddress: value.shippingAddress,
        items: from_candid_vec_n17(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productId: _ProductId;
    deliveryOption: _DeliveryOption;
    quantity: bigint;
    selectedSize: string;
}): {
    productId: ProductId;
    deliveryOption: DeliveryOption;
    quantity: bigint;
    selectedSize: string;
} {
    return {
        productId: value.productId,
        deliveryOption: from_candid_DeliveryOption_n15(_uploadFile, _downloadFile, value.deliveryOption),
        quantity: value.quantity,
        selectedSize: value.selectedSize
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    fulfillmentBy: _FulfillmentBy;
    name: string;
    description: string;
    hasFitAndTry: boolean;
    sizes: Array<string>;
    sellerName: string;
    orderCount: bigint;
    stock: bigint;
    imageUrl: string;
    hasSameDayDelivery: boolean;
    gender: string;
    category: string;
    sellerId: string;
    price: bigint;
}): {
    id: ProductId;
    fulfillmentBy: FulfillmentBy;
    name: string;
    description: string;
    hasFitAndTry: boolean;
    sizes: Array<string>;
    sellerName: string;
    orderCount: bigint;
    stock: bigint;
    imageUrl: string;
    hasSameDayDelivery: boolean;
    gender: string;
    category: string;
    sellerId: string;
    price: bigint;
} {
    return {
        id: value.id,
        fulfillmentBy: from_candid_FulfillmentBy_n27(_uploadFile, _downloadFile, value.fulfillmentBy),
        name: value.name,
        description: value.description,
        hasFitAndTry: value.hasFitAndTry,
        sizes: value.sizes,
        sellerName: value.sellerName,
        orderCount: value.orderCount,
        stock: value.stock,
        imageUrl: value.imageUrl,
        hasSameDayDelivery: value.hasSameDayDelivery,
        gender: value.gender,
        category: value.category,
        sellerId: value.sellerId,
        price: value.price
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    createdAt: bigint;
    isRead: boolean;
    orderId: [] | [string];
    message: string;
    sellerId: [] | [string];
}): {
    id: NotificationId;
    createdAt: bigint;
    isRead: boolean;
    orderId?: string;
    message: string;
    sellerId?: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        isRead: value.isRead,
        orderId: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.orderId)),
        message: value.message,
        sellerId: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.sellerId))
    };
}
function from_candid_tuple_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_OrderId, _Order]): [OrderId, Order] {
    return [
        value[0],
        from_candid_Order_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Processing: null;
} | {
    Shipped: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Delivered" in value ? OrderStatus.Delivered : "Confirmed" in value ? OrderStatus.Confirmed : "Cancelled" in value ? OrderStatus.Cancelled : "Processing" in value ? OrderStatus.Processing : "Shipped" in value ? OrderStatus.Shipped : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Card: null;
} | {
    CashOnDelivery: null;
}): PaymentMethod {
    return "Card" in value ? PaymentMethod.Card : "CashOnDelivery" in value ? PaymentMethod.CashOnDelivery : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SameDay: null;
} | {
    NextDay: null;
} | {
    Standard: null;
}): DeliveryOption {
    return "SameDay" in value ? DeliveryOption.SameDay : "NextDay" in value ? DeliveryOption.NextDay : "Standard" in value ? DeliveryOption.Standard : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Product;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Product;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Product_n25(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AdminFulfilled: null;
} | {
    SellerFulfilled: null;
}): FulfillmentBy {
    return "AdminFulfilled" in value ? FulfillmentBy.AdminFulfilled : "SellerFulfilled" in value ? FulfillmentBy.SellerFulfilled : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Seller;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Seller;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Order;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Order;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Order_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_OrderId, _Order]>): Array<[OrderId, Order]> {
    return value.map((x)=>from_candid_tuple_n39(_uploadFile, _downloadFile, x));
}
function to_candid_CartItem_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CartItem): _CartItem {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_DeliveryOption_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryOption): _DeliveryOption {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_FulfillmentBy_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FulfillmentBy): _FulfillmentBy {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fulfillmentBy: FulfillmentBy;
    name: string;
    description: string;
    hasFitAndTry: boolean;
    sizes: Array<string>;
    sellerName: string;
    stock: bigint;
    imageUrl: string;
    hasSameDayDelivery: boolean;
    gender: string;
    category: string;
    sellerId: string;
    price: bigint;
}): {
    fulfillmentBy: _FulfillmentBy;
    name: string;
    description: string;
    hasFitAndTry: boolean;
    sizes: Array<string>;
    sellerName: string;
    stock: bigint;
    imageUrl: string;
    hasSameDayDelivery: boolean;
    gender: string;
    category: string;
    sellerId: string;
    price: bigint;
} {
    return {
        fulfillmentBy: to_candid_FulfillmentBy_n22(_uploadFile, _downloadFile, value.fulfillmentBy),
        name: value.name,
        description: value.description,
        hasFitAndTry: value.hasFitAndTry,
        sizes: value.sizes,
        sellerName: value.sellerName,
        stock: value.stock,
        imageUrl: value.imageUrl,
        hasSameDayDelivery: value.hasSameDayDelivery,
        gender: value.gender,
        category: value.category,
        sellerId: value.sellerId,
        price: value.price
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productId: ProductId;
    deliveryOption: DeliveryOption;
    quantity: bigint;
    selectedSize: string;
}): {
    productId: _ProductId;
    deliveryOption: _DeliveryOption;
    quantity: bigint;
    selectedSize: string;
} {
    return {
        productId: value.productId,
        deliveryOption: to_candid_DeliveryOption_n5(_uploadFile, _downloadFile, value.deliveryOption),
        quantity: value.quantity,
        selectedSize: value.selectedSize
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FulfillmentBy): {
    AdminFulfilled: null;
} | {
    SellerFulfilled: null;
} {
    return value == FulfillmentBy.AdminFulfilled ? {
        AdminFulfilled: null
    } : value == FulfillmentBy.SellerFulfilled ? {
        SellerFulfilled: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Processing: null;
} | {
    Shipped: null;
} | {
    Pending: null;
} {
    return value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Confirmed ? {
        Confirmed: null
    } : value == OrderStatus.Cancelled ? {
        Cancelled: null
    } : value == OrderStatus.Processing ? {
        Processing: null
    } : value == OrderStatus.Shipped ? {
        Shipped: null
    } : value == OrderStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryOption): {
    SameDay: null;
} | {
    NextDay: null;
} | {
    Standard: null;
} {
    return value == DeliveryOption.SameDay ? {
        SameDay: null
    } : value == DeliveryOption.NextDay ? {
        NextDay: null
    } : value == DeliveryOption.Standard ? {
        Standard: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    Card: null;
} | {
    CashOnDelivery: null;
} {
    return value == PaymentMethod.Card ? {
        Card: null
    } : value == PaymentMethod.CashOnDelivery ? {
        CashOnDelivery: null
    } : value;
}
function to_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CartItem>): Array<_CartItem> {
    return value.map((x)=>to_candid_CartItem_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
